<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$requestId = "764f8b45-80a9-4538-a157-25310992397c";

curl_setopt($ch, CURLOPT_URL, "https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/{$requestId}");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_POSTFIELDS, "--verbose");

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Merchantid: af24002f-f265-4fd8-af62-20b6705bbc69';
$headers[] = 'Merchantkey: FWOXBIJYXNHROAGRXHMPFKJRSBQOYVVUQKVAMLQA';
$headers[] = "Requestid: $requestId";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

echo "<pre>";
echo $result;
echo "</pre>";
/* 
38366ddb-02f2-43ae-887f-b603a564e6a6
8783802e-7b33-4a0a-b495-5e28a60de12f
fab9f6a3-bd19-4568-86ea-62675ac5ab6e
cf6c4125-4314-438b-8d29-1568da06be9d
e98d8f11-c87e-4487-80ea-5ec3bc43a2a2 0704021828755
b78cf6de-20ab-4f05-92e4-ee3bf60c528d 0704022401861
b4535d9d-4660-40e3-8c55-d01a5b70da8c 0704022637851
ce2ec61c-8a56-4659-a109-aea44a17d4b4 
e2ffa78e-19e2-4809-9db5-c10d8a55e4b3 -|- 0704025444093
b59f6c0d-a085-4d79-b12a-fd2c2d9991ac -|- 0704030722394
d1b3a4c9-2eac-4fb9-af55-93b4571e63fe -|- 0704032514710
4eb43df4-3c24-4e1e-bdc9-83b1b8767dae
*/